apiVersion: v1
kind: Service
metadata:
  name: myflask-service
  labels:
    app: myflask-deploy
spec:
  type: NodePort
  selector:
    app: myflask-deploy
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30965